version: '3.8'

services:
  eureka-server:
    build:
      context: /Users/jose/Documents/GitHub/server  # Ruta completa al proyecto eureka-server
      dockerfile: Dockerfile  # El Dockerfile está en el directorio de eureka-server
    ports:
      - "8761:8761"
    networks:
      - eureka-network

  microservicio1:
    build:
      context: /Users/jose/Documents/GitHub/Microservicio1  # Ruta completa al proyecto microservicio1
      dockerfile: Dockerfile  # El Dockerfile está en el directorio de microservicio1
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge