version: '3.8'

services:
  eureka-server:
    build:
      context: /Users/jose/Documents/GitHub/server  # Ruta completa al proyecto eureka-server
      dockerfile: Dockerfile  # El Dockerfile está en el directorio de eureka-server
    ports:
      - "8761:8761"
    networks:
      - eureka-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - eureka-network

  microservicio1:
    build:
      context: /Users/jose/Documents/GitHub/Microservicio1  # Ruta completa al proyecto microservicio1
      dockerfile: Dockerfile  # El Dockerfile está en el directorio de microservicio1
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: password
    depends_on:
      - eureka-server
      - rabbitmq
    networks:
      - eureka-network

  microservicio2:
    build:
      context: /Users/jose/Documents/GitHub/Microservicio2  # Ruta completa al proyecto microservicio2
      dockerfile: Dockerfile  # El Dockerfile está en el directorio de microservicio2
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge