version: '3.8'

services:
  eureka-server:
    build:
      context: /Users/jose/Documents/GitHub/server  # Ruta completa al proyecto eureka-server
      dockerfile: Dockerfile  # El Dockerfile está en el directorio de eureka-server
    ports:
      - "8761:8761"
    networks:
      - eureka-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - eureka-network

  mysql:
    image: mysql:8.0
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P4ssword!
      MYSQL_DATABASE: my-app
    networks:
      - eureka-network

  microservicio1:
    build:
      context: /Users/jose/Documents/GitHub/Microservicio1  # Ruta completa al proyecto microservicio1
      dockerfile: Dockerfile  # El Dockerfile está en el directorio de microservicio1
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/my-app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: P4ssword!
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: true
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: true
    depends_on:
      - eureka-server
      - rabbitmq
      - mysql
    networks:
      - eureka-network

  microservicio2:
    build:
      context: /Users/jose/Documents/GitHub/Microservicio2  # Ruta completa al proyecto microservicio2
      dockerfile: Dockerfile  # El Dockerfile está en el directorio de microservicio2
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: true
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: true
    depends_on:
      - eureka-server
    networks:
      - eureka-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge