version: '3.8'

services:
  eureka-server:
    build:
      context: C:\Users\sgghu\Desktop\Universidad\server # Ruta completa al proyecto eureka-server
      dockerfile: Dockerfile  # El Dockerfile está en el directorio de eureka-server
    ports:
      - "8761:8761"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  rabbitmq2:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"   # Puerto para microservicio2
      - "15673:15672" # Puerto para la interfaz web
    environment:
      - RABBITMQ_DEFAULT_USER=user2
      - RABBITMQ_DEFAULT_PASS=password2

  microservicio1:
    build:
      context: C:\Users\sgghu\Desktop\Universidad\Microservicio1 # Ruta completa al proyecto microservicio1
      dockerfile: Dockerfile  # El Dockerfile está en el directorio de microservicio1
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
    depends_on:
      - eureka-server
      - rabbitmq

  microservicio2:
    build:
      context: C:\Users\sgghu\Desktop\Universidad\Microservicio2 # Ruta completa al proyecto microservicio2
      dockerfile: Dockerfile  # El Dockerfile está en el directorio de microservicio2
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5673
      - SPRING_RABBITMQ_USERNAME=user2
      - SPRING_RABBITMQ_PASSWORD=password2
    depends_on:
      - eureka-server
      - rabbitmq2
