global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'microservicio1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['microservicio1:8080']

  - job_name: 'microservicio2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['microservicio2:8081']

  - job_name: 'microservicio4'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'microservicio4:8083' ]

  - job_name: 'microservicio5'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'microservicio5:8084' ]

  - job_name: 'microservicio3'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'microservicio3:8082' ]